#!/bin/sh

echo "Checking for an older version in the system..."
if [ -d /usr/lib/enigma2/python/Plugins/Extensions/oroscopo ]
then
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/oroscopo > /dev/null 2>&1
echo "An older version was found and removed"
echo "Proceeding to installation..."
else
echo "Proceeding to installation..."
fi
exit 0
